services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./dev-php.ini:/usr/local/etc/php/conf.d/dev-php.ini
    environment:
      - DB_HOST=db
      - DB_PATH=/firebird/data/DB_SIDISTLOCAL.FDB
  db:
    platform: linux/amd64
    image: jacobalberty/firebird:2.5-sc
    ports:
      - "3050:3050"
    environment:
      - ISC_PASSWORD=masterkey
    volumes:
      - ./database:/firebird/data
